// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/sql;
import poc_step4.epfl;

listener http:Listener ep0 = new (9090, config = {host: "localhost"});

// Initialize the persist client from the epfl module
final epfl:Client persistClient = check new ();

service / on ep0 {
    # Liste des étudiants
    #
    # + actif - Filtrer par statut actif/inactif. Sans ce paramètre, tous les étudiants sont retournés.
    # + return - Liste retournée avec succès 
    resource function get etudiants(boolean? actif) returns EtudiantResponse[]|error {
        // Build the WHERE clause based on the actif parameter
        sql:ParameterizedQuery whereClause = actif is () ? `` : `actif = ${actif}`;
        
        // Retrieve students from the database using the persist client
        stream<epfl:Etudiant, error?> etudiantStream = persistClient->/etudiants(whereClause = whereClause);
        
        // Convert the stream to an array and map to EtudiantResponse
        epfl:Etudiant[] etudiants = check from epfl:Etudiant etudiant in etudiantStream
            select etudiant;
        
        // Map persist types to response types
        EtudiantResponse[] response = from epfl:Etudiant etudiant in etudiants
            select {
                id: etudiant.id,
                nom: etudiant.nom,
                prenom: etudiant.prenom,
                email: etudiant.email,
                actif: etudiant.actif
            };
        
        return response;
    }

    # Détail d'un étudiant
    #
    # + id - L'identifiant de l'étudiant
    # + return - returns can be any of following types 
    # http:Ok (Étudiant trouvé)
    # http:NotFound (Étudiant introuvable)
    resource function get etudiants/[int id]() returns EtudiantResponse|http:NotFound|error {
        // Retrieve the student by ID from the database
        epfl:Etudiant|error etudiant = persistClient->/etudiants/[id]();
        
        // Handle the case where the student is not found
        if etudiant is error {
            return http:NOT_FOUND;
        }
        
        // Map persist type to response type
        EtudiantResponse response = {
            id: etudiant.id,
            nom: etudiant.nom,
            prenom: etudiant.prenom,
            email: etudiant.email,
            actif: etudiant.actif
        };
        
        return response;
    }
}
